---
title: "Installation von R, Rstudio und Tidyverse"
output: github_document
---

## R und Rstudio

R ist eine Programmierungssprache, mit der wir Daten erheben, bearbeiten, visualisieren oder modellieren können. Rstudio ist eine Benutzeroberfläche, die das Steuern von R vereinfacht. 

Dieses [Seite](https://rstudio-education.github.io/hopr/starting.html) bietet detaillierte Einleitungen bezüglich der Installation von R und Rstudio (und [hier](https://www.youtube.com/watch?v=TFGYlKvQEQ4) als Video) an.

## Tidyverse

Als R installiert wird, werden nur Grundfunktionen installiert. Zum Beispiel, mathematische Operation wie Addition, Substraktion oder Division sind dann zugänglich. Im Rahmen des Seminars möchten wir aber komplexere Operation durchführen (zum Beispiel Daten visualisieren) und dazu benötigen wir externelle Funktionen, die als "package" genannt werden. 

Packages müssen einmal installiert werden und können dann so oft wie möglich bentuzt werden. 

Im Rahmen dieses Seminars brauchen wir das package [`Tidyverse`](https://www.tidyverse.org/), was mit folgendem Befehl installiert werden kann: `install.packages("tidyverse")`

Dieses [Video](https://www.youtube.com/watch?v=JBcVi-fAT_k) beschreibt wie man packages installieren kann. 



